### ISSUE TITLE
Error to install: Failed building wheel for llvmlite 

### ISSUE THREAD

**Issue by Rseq** [open2c/coolpuppy#25]
Hi, 

Many thanks for this tool. I have been using for a while, but I have issues now to install it on a new server:

command and error:
```
$ sudo -H pip install coolpuppy

Collecting coolpuppy
  Using cached https://files.pythonhosted.org/packages/1d/5b/670a1bd583e6af33c7e1b92512db35b9e8fa0b10f6c0756f0e41d9f570a5/coolpuppy-0.9.5-py3-none-any.whl
Collecting natsort (from coolpuppy)
  Using cached https://files.pythonhosted.org/packages/0f/65/81883897f4aaa1e53deaa65137318cfe80b36ce013c2e86f8fd0843cfa02/natsort-7.0.1-py3-none-any.whl
Collecting cooltools (from coolpuppy)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: cooler in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: Cython in /usr/local/lib/python3.6/dist-packages (from coolpuppy)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: bioframe<0.1.0 in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: cytoolz in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: click>=7 in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Collecting numba (from cooltools->coolpuppy)
Requirement already satisfied: tables in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.6/dist-packages (from cooltools->coolpuppy)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->coolpuppy)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas->coolpuppy)
Requirement already satisfied: h5py>=2.5 in /usr/local/lib/python3.6/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: asciitree in /usr/local/lib/python3.6/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: pypairix in /usr/local/lib/python3.6/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: pyfaidx in /usr/local/lib/python3.6/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cooler->coolpuppy)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->cooltools->coolpuppy)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->cooltools->coolpuppy)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->cooltools->coolpuppy)
Requirement already satisfied: pysam in /usr/local/lib/python3.6/dist-packages (from bioframe<0.1.0->cooltools->coolpuppy)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from bioframe<0.1.0->cooltools->coolpuppy)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from cytoolz->cooltools->coolpuppy)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->cooltools->coolpuppy)
Collecting llvmlite<0.35,>=0.34.0.dev0 (from numba->cooltools->coolpuppy)
  Using cached https://files.pythonhosted.org/packages/0b/96/07bfa93a103fb9e3e9ae7f9f7c6687ae714aee66b6f3000da3fad71e0aa2/llvmlite-0.34.0.tar.gz
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba->cooltools->coolpuppy)
Requirement already satisfied: numexpr>=2.6.2 in /usr/local/lib/python3.6/dist-packages (from tables->cooltools->coolpuppy)
Requirement already satisfied: dill>=0.3.2 in /usr/local/lib/python3.6/dist-packages (from multiprocess->cooltools->coolpuppy)
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vl4m588q/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgnvf90e2pip-wheel- --python-tag cp36:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-build-vl4m588q/llvmlite/ffi/build.py
  LLVM version... 6.0.0

  Traceback (most recent call last):
    File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 143, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '6.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

  error: command '/usr/bin/python3' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: natsort, llvmlite, numba, cooltools, coolpuppy
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vl4m588q/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-d57bdgeg-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-build-vl4m588q/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-vl4m588q/llvmlite/ffi/build.py
    LLVM version... 6.0.0

    Traceback (most recent call last):
      File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-vl4m588q/llvmlite/ffi/build.py", line 143, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '6.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vl4m588q/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-d57bdgeg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vl4m588q/llvmlite/
```

Using:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ python --version                                                                                                    
Python 3.6.9                                                                                                                                                            
$ cooler --version                                                                                                    
cooler, version 0.8.10                      
         
```

I tried: 
```
$ sudo -H pip install llvmlite
Collecting llvmlite
  Using cached https://files.pythonhosted.org/packages/50/cc/04526507e80d546be5688ce0246e40277b61e7949c3347c6609b6a4154cf/llvmlite-0.32.1.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fTS7N0/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpCT3Ui0pip-wheel- --python-tag cp27:
  running bdist_wheel
  /usr/bin/python /tmp/pip-build-fTS7N0/llvmlite/ffi/build.py
    File "/tmp/pip-build-fTS7N0/llvmlite/ffi/build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
  error: command '/usr/bin/python' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fTS7N0/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6jpcXq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-build-fTS7N0/llvmlite/llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
    running build_ext
    /usr/bin/python /tmp/pip-build-fTS7N0/llvmlite/ffi/build.py
      File "/tmp/pip-build-fTS7N0/llvmlite/ffi/build.py", line 122
        raise ValueError(msg.format(_ver_check_skip)) from e
                                                         ^
    SyntaxError: invalid syntax
    error: command '/usr/bin/python' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fTS7N0/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6jpcXq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fTS7N0/llvmlite/
```

I also tried:

https://www.reddit.com/r/Ubuntu/comments/g98cxm/help_installing_llvmlite_dependency_of_numba/
https://github.com/librosa/librosa/issues/757

No success so far. Any ideas?

Thank you for your time.

Best wishes

**Comment by Phlya** [comment]
Reading through the error message, looks like you need to upgrade LLVM to 9 or 10.

**Comment by Rseq** [comment]
Thanks for your feedback.
It happened to be pip itself that was outdated and could not build llvmlite.

```
$ sudo -H pip3 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 712kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-20.2.4

$ sudo -H pip3 install llvmlite
Collecting llvmlite
  Downloading llvmlite-0.34.0-cp36-cp36m-manylinux2010_x86_64.whl (24.6 MB)
     |████████████████████████████████| 24.6 MB 6.2 MB/s
Installing collected packages: llvmlite
Successfully installed llvmlite-0.34.0

```

Best wishes

**Comment by Phlya** [comment]
Glad it's solved!
