### ISSUE TITLE
installing older version of coolpuppy 

### ISSUE THREAD

**Issue by HHNNKK** [open2c/coolpuppy#38]
Hi,

I am trying to install the older version of coolpup wher the plotpup also works.

I have tried the new 0.9.7 version but get errpor when plotting.

can you kindly help me how should i get the older version and get the plot also.

**Comment by HHNNKK** [comment]
I did this:

pip install coolpuppy

[r596025@gene0001l001 pile_up_plot]$ coolpup.py -v
0.9.7

when i run the coolpup i get i a txt file and then potpup gives and error

[r596025@gene0001l001 pile_up_plot]$ plotpup.py --output loops.png /mnt/data/pile_up_plot/Ctrl_loop.txt
Traceback (most recent call last):
  File "/home/r596025/.local/bin/plotpup.py", line 33, in <module>
    sys.exit(load_entry_point('coolpuppy==0.9.7', 'console_scripts', 'plotpup.py')())
  File "/home/r596025/.local/lib/python3.6/site-packages/coolpuppy/__plotpuppy_main__.py", line 147, in main
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/home/r596025/.local/lib/python3.6/site-packages/coolpuppy/__plotpuppy_main__.py", line 147, in <listcomp>
    pups = [load_array_with_header(f)["data"] for f in args.pileup_files]
  File "/home/r596025/.local/lib/python3.6/site-packages/coolpuppy/coolpup.py", line 129, in load_array_with_header
    read_data = f.read()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by Phlya** [comment]
And check that the output file is actually a text file, that you can open in a any text editor and see the header and data.
Output from new versions is not text, so it should give you an error if you try to open it with a text editor.
