### ISSUE TITLE
Usage error

### ISSUE THREAD

**Issue by skytguuu** [open2c/coolpuppy#44]
Hi,

Thanks for your developed tool "coolpuppy". However, I met a problem when I used coolpup.py to draw the figures. It reported an error that "AttributeError: module 'bioframe' has no attribute 'make_viewframe'. It seems the problem is about the bioframe package. I have checked my conda list, bioframe(version=0.2.0) is already installed. 

Could u give me a hand?
Thanks!

**Comment by Phlya** [comment]
Hi, please update bioframe to 0.3, it was released recently.

**Comment by skytguuu** [comment]
Thanks for your help. But I want to use conda to update the bioframe, it is lack of 0.3.0 version. So I tried to download the latest released package 0.3.0, then python setup.py install. It succeed installed, but when I check the version of bioframe, it showed the version is still 0.2.0. Should I conda uninstall bioframe first, then to install or any other idea to solve it?
Thanks!

**Comment by Phlya** [comment]
Yeah uninstall with conda, and install with pip - the 0.3 version should be on PyPI.

**Comment by skytguuu** [comment]
Thanks, now I installed bioframe (0.3.0). However, it failed another error:
#############
TypeError: group() got an unexpected keyword argument 'dropna'
#############

**Comment by Phlya** [comment]
Can you please give the whole error message?

**Comment by skytguuu** [comment]
The whole error is:
![image](https://user-images.githubusercontent.com/25957174/135484277-7b8b9731-35ed-4420-831f-c8cc855f9587.png)

**Comment by Phlya** [comment]
Is your pandas also outdated? The dropna argument was introduced in 1.1, if you have some version below that please try updating pandas.

**Comment by skytguuu** [comment]
Now, I almost succeed. When I update pandas, it reported an error "ValueError: No column 'bins/weight'found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.". Then I cool banlance the matrix again, it succeed to run. However, I only got the one output file "test-20.0K_over_FGSC_20kb_DI_TAD_10-shifts_local.clpy". Is it right? Another question is about the cool balance, because I used the matrix which is alread balanced, but why it still need to be balanced? is it caused by my changed the version of python package?

I am aprreciated for your help!
Thanks!
"

**Comment by skytguuu** [comment]
This is the log of this running:

![image](https://user-images.githubusercontent.com/25957174/135491446-4f37322c-7a61-461a-af97-4407b95e82a3.png)

**Comment by Phlya** [comment]
Why do you expect multiple files? Looks like it worked!

Regarding balancing - how did you balance your data previously? How were the balancing weights stored?

**Comment by Phlya** [comment]
I don't know what happened with balancing then, that's strange.

How are you plotting? This is a very strange error... Can you share the pileup file?

**Comment by skytguuu** [comment]
Thanks for your help. I have updated my data to the google drive: "https://drive.google.com/file/d/19Rw0oppbBbNMcT9G56_eRf4FF_Ujxe12/view?usp=sharing", it is the .clpy output data.

I am still updated another input.bed and original balanced cool data and balanced cool data.

Thanks!

**Comment by skytguuu** [comment]
I have updated the input.bed file:"https://drive.google.com/file/d/1C_ndqzZ4plNWkC0ov4KjxfMpvpGBVKJC/view?usp=sharing",original balanced cool data: "https://drive.google.com/file/d/1S4FtSYwiSW57IbP9ThfYzgA2RkOwQx-4/view?usp=sharing" and balanced cool data: "https://drive.google.com/file/d/1S4FtSYwiSW57IbP9ThfYzgA2RkOwQx-4/view?usp=sharing".

Thanks for your help!

**Comment by Phlya** [comment]
Sorry I didn't get back to you regarding this, have you figured it out or should I have a look?

**Comment by sachingadakh** [comment]
Hello I received the error while plotting as mentioned above

 plotpup.py --input_pups 4DNFISUIYMOG50kb-50.0K_over_H1_hic_dekkerTADs_chrname_10-shifts_local_covnorm.clpy --output gamcool.pdf

Traceback (most recent call last):
  File "/home/sachin/.pyenv/versions/3.8.3/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/plotpuppy/CLI.py", line 205, in main
    pups = load_pileup_df_list(args.input_pups, quaich=args.quaich, nice_metadata=True)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 129, in load_pileup_df_list
    pups = pd.concat([load_pileup_df(path, quaich=quaich) for path in files])
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 129, in <listcomp>
    pups = pd.concat([load_pileup_df(path, quaich=quaich) for path in files])
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 90, in load_pileup_df
    for chunk in dstore.iter_chunks():

**Comment by sachingadakh** [comment]
2.10.0

**Comment by Phlya** [comment]
You need to update it to at least 3.0 then

**Comment by sachingadakh** [comment]
okay. Let me try. Thank you sir

**Comment by sachingadakh** [comment]
Now I am getting an Index error. I though this is may be issue with NumPy package, but it is not.

 plotpup.py --input_pups 4DNFISUIYMOG50kb-50.0K_over_H1_hic_dekkerTADs_chrname_10-shifts_local_covnorm.clpy --output gamcool.pdf

/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/coolpup.py:134: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pups["norm"][
/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/coolpup.py:311: RuntimeWarning: Mean of empty slice
  intra = np.nanmean(np.concatenate([amap[:i, :i].ravel(), amap[-i:, -i:].ravel()]))
/home/sachin/.local/lib/python3.8/site-packages/seaborn/axisgrid.py:382: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()
/home/sachin/.local/lib/python3.8/site-packages/seaborn/axisgrid.py:856: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.fig.tight_layout()
Traceback (most recent call last):
  File "/home/sachin/.pyenv/versions/3.8.3/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/plotpuppy/CLI.py", line 241, in main
    fg = make_heatmap_grid(
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 190, in make_heatmap_grid
    fg.map(add_score, "score")
  File "/home/sachin/.local/lib/python3.8/site-packages/seaborn/axisgrid.py", line 762, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/home/sachin/.local/lib/python3.8/site-packages/seaborn/axisgrid.py", line 846, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 100, in add_score
    s=f"{score.values[0]:.3g}",
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by sachingadakh** [comment]
> You need to update it to at least 3.0 then

Upgrade the version of h5py resolved that error. Thank you

**Comment by Phlya** [comment]
Strange error, would you be able to share the .clpy file?

**Comment by sachingadakh** [comment]
> Strange error, would you be able to share the .clpy file?

Sure. Let me share the google drive link to the file
https://drive.google.com/file/d/1mQRl5Z86iKqUTpK_6Z0tcRawxGS11U1f/view?usp=sharing

**Comment by Phlya** [comment]
It works for me, although the size of the pileup is really small, so the score is nan, and perhaps in an older version of coolpuppy it caused an error... Could you update to the latest version from the master branch please?

**Comment by sachingadakh** [comment]
> It works for me, although the size of the pileup is really small, so the score is nan, and perhaps in an older version of coolpuppy it caused an error... Could you update to the latest version from the master branch please?

I upgraded by pip install https://github.com/open2c/coolpuppy/archive/master.zip
but the same error with plotpup is persistent. Did you mean to calculate pileup again after upgrading the coolpuppy?

**Comment by Phlya** [comment]
Are you sure it got upgraded? To be sure, you can add these arguments to the pip command:
--upgrade --force-reinstall --no-cache-dir --no-deps

**Comment by Phlya** [comment]
I get a plot in the output, just the score is nan if you request it
[gamcool.pdf](https://github.com/open2c/coolpuppy/files/8224838/gamcool.pdf)

**Comment by sachingadakh** [comment]
Yes, I got the same plot with score nan after the upgrade but it is surprising to me since I used TADs from dekker lab to avarage them to analyse them within GAM Interaction matrices. I am using GAM contract matrix, not hic

**Comment by Phlya** [comment]
You probably need to use higher resolution

**Comment by sachingadakh** [comment]
The resoluation of GAM matrix is binned at 50 kb , it is not enough? I also have it for 20kb resolution data

**Comment by Phlya** [comment]
Without knowing more how exactly you ran coolpuppy I'm not sure I can help you definitively, but 20 kb should help anyway.

**Comment by sachingadakh** [comment]
The below one was my command:

coolpup.py ../../50KB/4DNFISUIYMOG50kb.cool H1_hic_dekkerTADs_chrname.bed --local --coverage_norm --clr_weight_name "" 

I was getting the below error when I applied the --scaled_pad parameter.

Error:          coolpup.py: error: argument --rescale_flank/--rescale_pad: expected one argument
command : coolpup.py ../../50KB/4DNFISUIYMOG50kb.cool H1_hic_dekkerTADs_chrname.bed --rescale_pad --local --coverage_norm --clr_weight_name "" 

I will try using 20kb binned matrix

**Comment by Phlya** [comment]
If these are whole TADs you want to see, you need to add --rescale

**Comment by sachingadakh** [comment]
The below error when I used 20 KB binned matrix

coolpup.py ../../20kb/4DNFI2JYAURZ.cool H1_hic_dekkerTADs_chrname.bed --local --coverage_norm --clr_weight_name ""
Traceback (most recent call last):
  File "/home/sachin/.pyenv/versions/3.8.3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 315, in main
    parser = parse_args_coolpuppy()
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 105, in parse_args_coolpuppy
    parser.add_argument(
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'target'

**Comment by Phlya** [comment]
Did you also update coolpuppy between the runs? I made a mistake in one of the recent commits, fixed now, can you update and try again?

**Comment by Phlya** [comment]
Sorry, that's another recent change that introduced a bug for unbalanced data... Not a common use case for me, sorry. Could you update and try again?

**Comment by sachingadakh** [comment]
Besides would it be possible to dump the piled up aggregated interactions from .clpy to txt format? So I can maybe attempt to plot by myself in R using dumped .clpy data.

**Comment by Phlya** [comment]
What do you mean output us none? Do you get a plot? What is it?

**Comment by Phlya** [comment]
You can read the data in python, and then dump to txt using np.savetxt. Or you can read the data directly into R, since it's just an HDF5 file, but I can't help much since I am not experienced with R.

**Comment by sachingadakh** [comment]
> What do you mean output us none? Do you get a plot? What is it?

I did get the plot, sir but it doesn't have a proper visualization of piled up contact matrix and scaled TADs, that's why I shared the flags with you earlier for reference. The output plot is almost same as I got it earlier for the 50kb binned data matrix

**Comment by sachingadakh** [comment]
> You can read the data in python, and then dump to txt using np.savetxt. Or you can read the data directly into R, since it's just an HDF5 file, but I can't help much since I am not experienced with R.

Sure. I will try reading it on R. Thank you very much

**Comment by Phlya** [comment]
If you want to see TADs, you need to add --rescale argument to coolpup.py

**Comment by sachingadakh** [comment]
Thank you. I am attempting again with --rescale parameter now

**Comment by sachingadakh** [comment]
Hello Sir,
   I got now far more improved plot. Thank you for your cooperation.
 I could see the strength of interaction at the TAD border. However it still looks pretty sparse in the background, I meant background interactions are not as visible as they are in the plots showcased 
 here : thttps://coolpuppy.readthedocs.io/en/latest/walkthrough.html#local-pileups 

Can you see my plot and recommend me what I am lacking to provide in terms of supporting data etc.
[gam20scaledtad.pdf](https://github.com/open2c/coolpuppy/files/8245091/gam20scaledtad.pdf)

**Comment by Phlya** [comment]
I think your plot looks very good. Especially it's not Hi-C data, so details might look different, but this is great.

**Comment by sachingadakh** [comment]
Thank you very much for the validation sir. 

I am wondering if I should use the --rescale_pad parameter. I want to see how scaled TAD would look when flanked on each side by a region of the same size, but I am getting the following error when I use --rescale_pad or --rescale_flank parameter

coolpup.py ../../20kb/4DNFI2JYAURZ.cool H1_hic_dekkerTADs_chrname.bed --local --coverage_norm --clr_weight_name "" --rescale_pad

coolpup.py: error: argument --rescale_flank/--rescale_pad: expected one argument

**Comment by Phlya** [comment]
>how scaled TAD would look when flanked on each side by a region of the same size

That is exactly what you get by default. You can choose a different value, e.g. flank TADs with double their size with `--rescale_flank 2`

**Comment by sachingadakh** [comment]
> Sounds good!

Thank you sir again. I really appreciate your cooperation. I shall keep you in the loop.
