### ISSUE TITLE
coolpup error

### ISSUE THREAD

**Issue by skytguuu** [open2c/coolpuppy#45]
Hi,

Thanks for your wonderful developed tool "coolpup.py", however I met a problem when I tried to use coolpup.py to calculate the average TAD. The error is as followed:

#################
Traceback (most recent call last):
  File "/home/dell/softwares/anaconda2/envs/cooltools/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/dell/softwares/anaconda2/envs/cooltools/lib/python3.7/site-packages/coolpuppy/__main__.py", line 535, in main
    pup, n = PU.pileupsWithControl(nproc)
  File "/home/dell/softwares/anaconda2/envs/cooltools/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1160, in pileupsWithControl
    loops, nums, cov_starts, cov_ends, ns = list(zip(*mymap(f, self.chroms)))
  File "/home/dell/softwares/anaconda2/envs/cooltools/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1131, in pileup_chrom
    mids=mids, chrom=chrom, expected=expected,
  File "/home/dell/softwares/anaconda2/envs/cooltools/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1002, in _do_pileups
    if stBin > endBin:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
######################
Could you give me a hand?

Thanks

**Comment by Phlya** [comment]
Sorry for not replying - I think this error shouldn't appear now, did it get solved?

**Comment by skytguuu** [comment]
Thanks for your help. The problem is happend because of the input data of TADs. If I have less TADs, such as 80 TADs. It will reported the error. If I changed other TADs data such as 1000 TADs, it worked well.

**Comment by Phlya** [comment]
I see! Strange, it shouldn't happen. But I guess this can be closed?

**Comment by skytguuu** [comment]
Sure, thanks for your help.
