### ISSUE TITLE
pileup error and plot warning

### ISSUE THREAD

**Issue by yhx-tj** [open2c/coolpuppy#46]
Hi,

Thanks for this efficient tools, I met a little problem after updating coolpuppy to the lasted version 0.9.7.

Command:
`coolpup.py ${cool} loops.bedpe --n_proc 8 --pad 100 --expected expected.tsv --outname pileup.hdf`

Error messages:
```
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'chr1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/anaconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 454, in main
    PU = PileUpper(
  File "~/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1301, in __init__
    region = self.view_df.loc[region_name]
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'chr1'
```
It can only run when I removed the --expected option. The version of cooler and cooltools are 0.8.11 and 0.4.0, respectively.

The first few lines of expected:

> region	diag	n_valid	count.sum	balanced.sum	count.avg	balanced.avg
> chr1	0	43655	nan	nan	nan	nan
> chr1	1	43343	nan	nan	nan	nan
> chr1	2	43302	12718366.0	1376.1829404740088	293.71313103320864	0.03178104799949214
> chr1	3	43266	7097409.0	772.2076981451341	164.04125641381222	0.017847910556675776
> chr1	4	43236	4864835.0	529.6801545724658	112.51815616615784	0.012250905601176467
> chr1	5	43216	3692672.0	401.46740688818664	85.44687152906332	0.00928978634968962
> chr1	6	43198	2977267.0	322.82954176512936	68.92140839853697	0.007473252043268886
> chr1	7	43178	2505831.0	270.81543204213733	58.034902033442954	0.0062720698513626695
> chr1	8	43162	2176667.0	234.55833800151692	50.43017005699458	0.005434371391536929

Finally, I used plotpuppy to visualize the results:
`plotpup.py --output pileup.png --input_pups pileup1.hdf pileup2.hdf ... pileupN.hdf`

Errors:
```
~/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py:132: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pups["norm"][
~/anaconda3/lib/python3.8/site-packages/seaborn/axisgrid.py:64: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.fig.tight_layout(*args, **kwargs)
Traceback (most recent call last):
  File "~/anaconda3/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.8/site-packages/plotpuppy/CLI.py", line 235, in main
    fg = make_heatmap_grid(
  File "~/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 187, in make_heatmap_grid
    fg.map(add_heatmap, "data", norm=norm, cmap=cmap)
  File "~/anaconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 684, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "~/anaconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 774, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "~/anaconda3/lib/python3.8/site-packages/plotpuppy/plotpup.py", line 79, in add_heatmap
    raise ValueError(
ValueError: Multiple pileups for one of the conditions, ensure unique correspondence for each col/row combination
```
How to specify the command line to draw multiple pileups at once?

Thank you so much for your help!

**Comment by Phlya** [comment]
Sorry for not replying, did you figure this out?

**Comment by chenggang108** [comment]
Hi @yhx-tj, 

I meet the same error recently. Did you figure out the problem?

Thanks

**Comment by chenggang108** [comment]
Hi @yhx-tj, 

I meet the same error recently. Did you figure out the problem?

Thanks
