### ISSUE TITLE
Problem in the dimenision/indexing of snips df

### ISSUE THREAD

**Issue by Abeer-hes** [open2c/coolpuppy#50]
Hello guys,

Sorry for the naive issue but I am struggling long with this error that might be stemming from irregularities in the snips dataframe from my data (could be the nan or disperse regions?).
The line I am running is:

`cooler balance --ignore-diags 0   WT_inter_30_5000_sorted.cool`

`cooltools compute-expected --nproc 6 --ignore-diags 0  --output WT_inter_30_5000_sorted.tsv   WT_inter_30_5000_sorted.cool`

`coolpup.py  --pad 100 --n_proc 6 --mindist 5000  --outname Wt_EnhancerPredictions_all --expected WT_inter_30_5000_sorted.tsv --ignore_diags 0  --ooe False   WT_inter_30_5000_sorted.cool EnhancerPredictions_u.bedpe`

The error I am receiving:

`Traceback (most recent call last):
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scn-4/anaconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 454, in main
    PU = PileUpper(
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1301, in __init__
    region = self.view_df.loc[region_name]
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: '1'`

if I remove the expected values of my cooler, this is what it throws back:

`coolpup.py  --pad 100 --n_proc 6 --mindist 5000  --outname Wt_EnhancerPredictions_all  --ignore_diags 0  --ooe False   WT_inter_30_5000_sorted.cool EnhancerPredictions_u.bedpe`

`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/scn-4/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/scn-4/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1653, in pileup_region
    final = self.accumulate_stream(
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1590, in accumulate_stream
    for snip in collapse(snip_stream, base_type=pd.Series):
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/more_itertools/more.py", line 1064, in collapse
    yield from walk(iterable, 0)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/more_itertools/more.py", line 1061, in walk
    for child in tree:
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1510, in _stream_snips
    data[D] = np.nan
IndexError: boolean index did not match indexed array along dimension 0; dimension is 31 but corresponding boolean dimension is 41
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scn-4/anaconda3/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/CLI.py", line 507, in main
    pups = PU.pileupsWithControl(nproc)
  File "/home/scn-4/anaconda3/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 1705, in pileupsWithControl
    pileups = list(mymap(f, self.view_df.index))
  File "/home/scn-4/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/scn-4/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: boolean index did not match indexed array along dimension 0; dimension is 31 but corresponding boolean dimension is 41
`

 My files are:

https://drive.google.com/file/d/1t85GtqoAj2mF0fJ2-4dUP6B0kjozSJYi/view?usp=sharing
https://drive.google.com/file/d/1qtoKsEfeZzhHmZujqALUVEBkzsUYrplw/view?usp=sharing
https://drive.google.com/file/d/1RXZfO6zPc54t2shiukKfLJEvwFuamdp-/view?usp=sharing

Any help or suggestion of what I am doing wrong will be greatly appreciated.

**Comment by Phlya** [comment]
Hi, could you try upgrading to the latest version of cooltools and the recent coolpuppy from github? Note you have to change some arguments in the commands then... In particular, don't forget to change the --pad/--flank argument in coolpup.py to be base pairs, not kbp.

I think this can be caused by having numerical chromosomes in older versions (i.e. just 1, not chr1, etc)...

**Comment by Abeer-hes** [comment]
Hello @Phlya 

Great thanks for the fast reply. It works now after the updates, but only when I provide seed value, otherwise, with the same line and input data, it works few times and thraws an error most of the times (might have to do with randomness of picking control snips..). I am trying to make it work with expected (still thrawing same error) after changing the names of chrom of my matrix (bit tricky being limited to commandline, trying to repurpose the rename_chrom function from cooler creat.py to use from terminal) which might be better solution since I am having noisy pileups from my .cool and regions so far.

Best,

**Comment by Phlya** [comment]
I assume it is resolved now! Feel free to reopen if you still have issues.
