### ISSUE TITLE
KeyError: 'coordinates'

### ISSUE THREAD

**Issue by iagooteroc** [open2c/coolpuppy#68]
Hello, I'm trying to run coolpup.py with the latest github version like this:
```
coolpup.py ${balanced_cooler} ${interactions} \
    --features_format bedpe --expected ${expected_file} \
    --ignore_diags 0 --flank 200000 \
    --outname ${clpy_file} \
    --nproc 4
```
But I get the following error: 

```
INFO:root:Namespace(cool_path='/mnt/netapp2/mobilegenomes/1/1_projects/1022_CELL-LINES-HiC/2_alignment/Micro-C_H2009_lib1/Micro-C_H2009_lib1_15k_bal.cool', features='clearly_somatic/offset_mei_1000_promoter_100/regions.bedpe', features_format='bedpe', view=None, flank=200000, minshift=100000, maxshift=1000000, nshifts=10, expected=('Micro-C_15k_expected_cis.tsv', 'balanced.avg'), ooe=True, mindist=None, maxdist=None, ignore_diags=0, excl_chrs='chrY,chrM', incl_chrs='all', subset=0, by_window=False, by_strand=False, by_distance=False, flip_negative_strand=False, local=False, coverage_norm=False, trans=False, by_chroms=False, store_stripes=False, rescale=False, rescale_flank=1.0, rescale_size=99, clr_weight_name='weight', n_proc=4, outname='local_clearly_somatic_pileup_expected.clpy', seed=None, logLevel='INFO', post_mortem=False)
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:478: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  intervals["exp_start1"] = (
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:481: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  intervals["exp_end1"] = (
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:484: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  intervals["exp_start2"] = (
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:487: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  intervals["exp_end2"] = (
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:886: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  intervals2d["kind"] = "ROI"
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/CLI.py:488: UserWarning: Can't do both expected and control shifts; defaulting to expected
  PU = PileUpper(
INFO:root:('chr3', 'chr3'): 5
INFO:root:('chr7', 'chr7'): 11
INFO:root:('chr5', 'chr5'): 11
INFO:root:('chr1', 'chr1'): 11
INFO:root:('chr8', 'chr8'): 4
INFO:root:('chr6', 'chr6'): 3
INFO:root:('chr4', 'chr4'): 2
INFO:root:('chr9', 'chr9'): 5
INFO:root:('chr13', 'chr13'): 2
INFO:root:('chr11', 'chr11'): 7
INFO:root:('chr14', 'chr14'): 1
INFO:root:('chr2', 'chr2'): 15
INFO:root:('chr10', 'chr10'): 6
INFO:root:('chr12', 'chr12'): 4
INFO:root:('chr15', 'chr15'): 3
INFO:root:('chr20', 'chr20'): 3
INFO:root:('chr17', 'chr17'): 7
INFO:root:('chr19', 'chr19'): 2
INFO:root:('chr16', 'chr16'): 1
INFO:root:('chrX', 'chrX'): 3
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'coordinates'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/frame.py", line 3799, in _set_item_mgr
    loc = self._info_axis.get_loc(key)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cesga/2020/software/Core/python/3.9.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/cesga/2020/software/Core/python/3.9.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py", line 1791, in pileup_region
    final = self.accumulate_stream(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py", line 1712, in accumulate_stream
    for snip in collapse(snip_stream, base_type=dict):
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/more_itertools/more.py", line 1223, in collapse
    yield from walk(iterable, 0)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/more_itertools/more.py", line 1220, in walk
    for child in tree:
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py", line 1517, in _stream_snips
    row1 = next(intervals)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py", line 1195, in get_intervals_stream
    intervals["coordinates"] = intervals.apply(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/frame.py", line 3645, in __setitem__
    self._set_item_frame_value(key, value)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/frame.py", line 3788, in _set_item_frame_value
    self._set_item_mgr(key, arraylike)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/frame.py", line 3802, in _set_item_mgr
    self._mgr.insert(len(self._info_axis), key, value)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1235, in insert
    raise ValueError(
ValueError: Expected a 1D array, got an array with shape (0, 22)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/bin/coolpup.py", line 33, in <module>
    sys.exit(load_entry_point('coolpuppy==0.9.7', 'console_scripts', 'coolpup.py')())
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/CLI.py", line 545, in main
    pups = PU.pileupsWithControl(nproc)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py", line 1852, in pileupsWithControl
    pileups = list(p.starmap(f, zip(listchr1, listchr2)))
  File "/opt/cesga/2020/software/Core/python/3.9.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/cesga/2020/software/Core/python/3.9.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Expected a 1D array, got an array with shape (0, 22)
```

Any idea what could be the cause? Maybe something to do with chrY?
Thank you.

**Comment by efriman** [comment]
Hi! Thanks for uploading the whole error. I'm not quite sure but seems it's something related to the regions file. Could you maybe upload the bedpe file so I could have a look? Also, could you try running the command with --nproc 1 instead of 4?

Is this the first time you are using coolpup.py or have you managed with other files?

**Comment by iagooteroc** [comment]
Hello @efriman! Thank you for answering even though is Saturday.
I was able to avoid the error by adding `--excl_chrs 'chrY,chrM,chr21,chr22'`
However, the resulting plot is empty, so I'm probably doing something wrong with the regions file as you suggest:
[regions.txt](https://github.com/open2c/coolpuppy/files/8747810/regions.txt)
(Changed to .txt so I could upload, but it is .bedpe)

Yes, it is the first time I'm using coolpup.py

**Comment by efriman** [comment]
I'm not sure this is everything but some of these regions are outside the bounds of at least the mouse genome, which is causing the same error for me. Try to double check and filter out such regions and see if that solves it.

**Comment by iagooteroc** [comment]
I'm using the human [GCA_000001405.15_GRCh38_no_alt_analysis_set.fna](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids) as reference, so every region is inside the bounds. Nevertheless, I removed the following region:
> chr16  78204879  78204879  chr8  144950808  144950808

As it is less than 200kb away from the chr8 boundary. This is the output:

```
INFO:root:Namespace(cool_path='/mnt/netapp2/mobilegenomes/1/1_projects/1022_CELL-LINES-HiC/2_alignment/Micro-C_H2009_lib1/Micro-C_H2009_lib1_15k_bal.cool', features='clearly_somatic/offset_mei_1000_promoter_100/regions.bedpe', features_format='bedpe', view=None, flank=200000, minshift=100000, maxshift=1000000, nshifts=10, expected=('Micro-C_15k_expected_cis.tsv', 'balanced.avg'), ooe=True, mindist=None, maxdist=None, ignore_diags=0, excl_chrs='chrY,chrM,chr21,chr22', incl_chrs='all', subset=0, by_window=False, by_strand=False, by_distance=False, flip_negative_strand=False, local=False, coverage_norm=False, trans=False, by_chroms=False, store_stripes=False, rescale=False, rescale_flank=1.0, rescale_size=99, clr_weight_name='weight', n_proc=1, outname='local_clearly_somatic_pileup_expected.clpy', seed=None, logLevel='DEBUG', post_mortem=False)

/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/CLI.py:488: UserWarning: Can't do both expected and control shifts; defaulting to expected
  PU = PileUpper(
INFO:root:('chr1', 'chr1'): 11
INFO:root:('chr2', 'chr2'): 15
INFO:root:('chr3', 'chr3'): 5
INFO:root:('chr4', 'chr4'): 2
INFO:root:('chr5', 'chr5'): 11
INFO:root:('chr6', 'chr6'): 3
INFO:root:('chr7', 'chr7'): 11
INFO:root:('chr8', 'chr8'): 4
INFO:root:('chr9', 'chr9'): 5
INFO:root:('chr10', 'chr10'): 6
INFO:root:('chr11', 'chr11'): 7
INFO:root:('chr12', 'chr12'): 4
INFO:root:('chr13', 'chr13'): 2
INFO:root:('chr14', 'chr14'): 1
INFO:root:('chr15', 'chr15'): 3
INFO:root:('chr16', 'chr16'): 1
INFO:root:('chr17', 'chr17'): 7
INFO:root:('chr19', 'chr19'): 2
INFO:root:('chr20', 'chr20'): 3
INFO:root:('chrX', 'chrX'): 3
INFO:root:Total number of piled up windows: 106
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/coolpuppy/coolpup.py:50: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['n', 'num', 'clr', 'rescale_flank', 'chroms', 'seed', 'clr_weight_name',
       'expected_value_col'],
      dtype='object')]

  df[df.columns[df.columns != "data"]].to_hdf(filename, "annotation", mode=mode)
INFO:root:Saved output to local_clearly_somatic_pileup_expected.clpy
```
Then, to plot the result, I'm trying:
```
plotpup.py \
    --output plot/clearly_somatic_pup_expected.png \
    --input_pups ${clpy_file} \
    --no_score --height 1.5
```

But I get this error:
```
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/plotpuppy/plotpup.py:74: RuntimeWarning: All-NaN slice encountered
  vmax = np.nanmax(comb)
/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/plotpuppy/plotpup.py:75: RuntimeWarning: All-NaN slice encountered
  vmin = np.nanmin(comb)
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/bin/plotpup.py", line 33, in <module>
    sys.exit(load_entry_point('coolpuppy==0.9.7', 'console_scripts', 'plotpup.py')())
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/plotpuppy/CLI.py", line 299, in main
    fg = make_heatmap_grid(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/plotpuppy/plotpup.py", line 504, in make_heatmap_grid
    plt.draw()
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/pyplot.py", line 973, in draw
    gcf().canvas.draw_idle()
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/figure.py", line 2837, in draw
    mimage._draw_list_compositing_images(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/image.py", line 547, in _make_image
    output = self.norm(resampled_masked)
  File "/mnt/lustre/scratch/nlsas/home/usc/mg/ioc/python_3.9.9/cool/lib/python3.9/site-packages/matplotlib/colors.py", line 1541, in __call__
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
```
If I add `--cmap fall --vmax 0.1 --vmin 0.001` then it runs, but results in an empty plot.

By the way, the expected file starts like this:
```
region1	region2	dist	n_valid	count.sum	balanced.sum	count.avg	balanced.avg
chr1	chr1	0	14357	nan	nan	nan	nan
chr1	chr1	1	14280	nan	nan	nan	nan
chr1	chr1	2	14241	872249.0	400.68168585150886	61.24913980759778	0.02813578301042826
chr1	chr1	3	14214	578600.0	264.5057736352186	40.70634585619811	0.018608820433039158
chr1	chr1	4	14191	446960.0	203.5649331873679	31.496018603340143	0.014344650354969199
chr1	chr1	5	14173	368041.0	167.2232859466685	25.967755591617866	0.011798721932312742
chr1	chr1	6	14159	315027.0	142.8464970581645	22.24924076559079	0.010088741935035277
```

I suppose the starting nan's are normal? I generated it like this:
```
cooltools expected-cis -p ${threads} \
    -o ${expected_file} ${balanced_cooler}
```

Sorry for the long post!

**Comment by efriman** [comment]
So I think I found the source of the first issue, which is not actually with chromosome bounds but that the two regions in the .bedpe file are two close together (within 2*resolution limit). Can you try to make a new bedpe file filtering those out that are too close and try again? In that case you should not have to use --excl_chrs or anything like that. I don't think your expected is any problem.

For example, you can filter out using: awk '{if((sqrt(($5-$2)*($5-$2))>10000)) {print $0}}' regions.txt | bedtools sort -i > regions_filtered.bedpe

Where 10000 is for 5kb resolution in this case (so increase accordingly).

This is definitely a bug we will fix.

**Comment by iagooteroc** [comment]
Thank you so much! That fixed everything!

**Comment by iagooteroc** [comment]
Hello again, sorry to reopen this when the issue has been solved, but I wanted to know your opinion about the resulting plot and I don't have your email.
My regions are Mobile element insertions (MEIs) that have Micro-C contact with promoters. 
[Does the plot make sense?](https://ibb.co/Yp3f774)
The Micro-C cooler file has now 5kb resolution and I plotted it using these parameters:
```
coolpup.py ${balanced_cool} ${no_dig_inter} \
    --features_format bedpe --expected ${expected_file} \
    --ignore_diags 0 --flank 150000 --mindist 0 \
    --outname ${clpy_file}
plotpup.py \
    --output ${plot_file} \
    --input_pups ${clpy_file} \
    --height 1.5
```
Would you say that there are more interactions than expected given the center pixel has a score of 6.52?
Could it be entirely because the interactions are with a promoter region, having nothing to do with MEIs?
My email is i.otero.coto@gmail.com if you prefer to discuss over email.

Thank you very much,
Iago.

**Comment by Phlya** [comment]
Such high enrichment in a single pixel is most likely an artefact (FYI the default label in the corner is average of the central 3x3 pixels, and the actual value must be what's on top of the colour bar, which is impossibly high). Are MEIs some kind of repeats? I'd guess it's a multi-mapping artefact. Have you filtered your pairs by mapq? That can help.

In general, due to the polymeric nature of chromatin, neighbouring pixels should have similar values, and transitions in contacts patterns are smooth. So if you observe something very sharp, it's likely to be an artefact of some sort.

**Comment by efriman** [comment]
The error you encountered should now be fixed in the newest update, so you shouldn't have to do any filtering. Hope you makes sense of your data!
