### ISSUE TITLE
plotpup.py TypeError: __init__() got an unexpected keyword argument 'add_all'

### ISSUE THREAD

**Issue by odovgusha** [open2c/coolpuppy#73]
Hi, thank you for helping with previous issue.

after running the coolpup 
coolpup.py $FOLDER/file.cool --outname $FOLDER/file.cool_out $FOLDER/encode_chipseq.bed
I ve get a cool_out file which is quite small in size (attached in zip)

and after running the plotpup.py
plotpup.py $FOLDER/file.cool_out --output $FOLDER/test.png

I get 
Traceback (most recent call last):
  File "/usr/users/odovgus1/miniconda3/bin/plotpup.py", line 8, in <module>
    sys.exit(main())
  File "/usr/users/odovgus1/miniconda3/lib/python3.7/site-packages/coolpuppy/__plotpuppy_main__.py", line 202, in main
    cbar_pad="3%",
TypeError: __init__() got an unexpected keyword argument 'add_all'

Do you have any suggestions? I have the log file and the cool_out file in zip attached. Thanks!
[files.zip](https://github.com/open2c/coolpuppy/files/8878315/files.zip)

**Comment by efriman** [comment]
Hi, 
You are using an old version of the software so it's hard to troubleshoot. Please do a clean install with the latest release and hopefully that will solve it!

**Comment by JosephAguilera** [comment]
> Hi, thank you for helping with previous issue.
> 
> after running the coolpup coolpup.py $FOLDER/file.cool --outname $FOLDER/file.cool_out $FOLDER/encode_chipseq.bed I ve get a cool_out file which is quite small in size (attached in zip)
> 
> and after running the plotpup.py plotpup.py $FOLDER/file.cool_out --output $FOLDER/test.png
> 
> I get Traceback (most recent call last): File "/usr/users/odovgus1/miniconda3/bin/plotpup.py", line 8, in sys.exit(main()) File "/usr/users/odovgus1/miniconda3/lib/python3.7/site-packages/coolpuppy/**plotpuppy_main**.py", line 202, in main cbar_pad="3%", TypeError: **init**() got an unexpected keyword argument 'add_all'
> 
> Do you have any suggestions? I have the log file and the cool_out file in zip attached. Thanks! [files.zip](https://github.com/open2c/coolpuppy/files/8878315/files.zip)

Hello odovgusha, 

I am not too sure if you have solved this issue, but I received the exact same error, and what solved it for me was downgrading matplotlib to 3.3.4. Hope this helps!

Best, 
Joseph
