### ISSUE TITLE
How to deal with KeyError and ValueError?

### ISSUE THREAD

**Issue by Soh-hyon** [open2c/coolpuppy#89]
I have trouble drawing APA plot using FitHiChIP output file, "shared.clean.loops"
coolpup.py works well with **unique.loops.bedpe** file, but it reports errors when **shared.clean.loops** is used as an input. The following is what I entered and what I got:

### input command
coolpup.py H3K27ac_veh_matrix_5kb.cool FitHiChIP_result_shortcut/shared.clean.loops --clr_weight_name --coverage_norm -p 24 -o APA/veh_matrix.vs.shared_loops.txt

### output
Traceback (most recent call last):
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/bioframe/io/fileops.py", line 68, in read_table
    kwargs.setdefault("names", SCHEMAS[schema])
KeyError: 'loops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/coolpuppy/CLI.py", line 413, in main
    features = bioframe.read_table(
  File "/media/nepi/vol_1/nepi_account/nepi_SH/.local/lib/python3.8/site-packages/bioframe/io/fileops.py", line 71, in read_table
    raise ValueError("TSV schema not found: '{}'".format(schema))
ValueError: TSV schema not found: 'loops'

**Comment by efriman** [comment]
Hi, 

Try running with '--feature_format bedpe' or changing the file ending to '.bedpe'. 

Elias

**Comment by Soh-hyon** [comment]
It worked!
Thank you

Soh-hyon
